### ISSUE TITLE
TeX コーディングに関する問題

### ISSUE THREAD

**Issue by kokic** [Seasawher/Seasawher#6]
ご迷惑をおかけして申し訳ありません。

私は日本語で書かれた記事を読むことを試みていますが、私は日本語の母国語話者ではありませんし、日本語が得意ではありません。ほとんどの場合、翻訳ソフトウェアを使用して内容を読むことができます。しかし、これは常に可能ではありません。[「基本群に映る双曲的代数曲線の構造」](https://www.kurims.kyoto-u.ac.jp/~motizuki/Kihongun%20ni%20utsuru%20soukyokuteki%20kyokusen%20no%20kouzou.pdf) のような文書に遭遇すると、通常の記事と見た目には違いがないようですが、実際には文字内容（ASCII 文字以外）を正しく取得することができません。これはある種のコーディング問題であり、TeX ファイルを pdf にエクスポートする際に、作成者が正しい方法でエクスポートしなかったためです。

私もいくつかの可能性のある方法を試してみました。例えば：

- html や docx などの他の文書に変換する。
- OCR を使用する。これは効率的な方法ではありません。（この点について、一般的に受け入れられている事実として、日本語のスキャン認識は他の言語よりも困難です。さらに数学式が存在します。機械学習ベースの「式-テキスト」混合スキャンツールは非常に優れていますが、現在では日本語に対応していません。）

私が尋ねたいのは、上記のようなファイルについて、内容を正しく読み取る方法は何かありますか？これが純粋なコーディング問題であれば、「デコード」することができる程度であれば理想的です。

に感謝。

**Comment by Seasawher** [comment]
Hello. I'm grad to receive your message.

You are probably more familiar with English than with Japanese, so I will write in English.

The message you have sent me, in other words, is it about the following?

* You want to read PDFs in Japanese on mathematics, including [this](https://www.kurims.kyoto-u.ac.jp/~motizuki/Kihongun%20ni%20utsuru%20soukyokuteki%20kyokusen%20no%20kouzou.pdf)

* You are not fluent in Japanese and would like to use a translation tool, but are having trouble applying it

* You want to know how to convert PDFs into a form that translation tools can use

---

I have checked the [PDF you gave as an example](https://www.kurims.kyoto-u.ac.jp/~motizuki/Kihongun%20ni%20utsuru%20soukyokuteki%20kyokusen%20no%20kouzou.pdf) and it is indeed difficult to apply translation tools to it as it is garbled when copied.

I didn't know how to fix it, so I looked into it too, but didn't find an effective solution.

I can only suggest using OCR, as you say ... sorry.

**Comment by kokic** [comment]
Thank you very much for your reply! Your understanding is completely correct. 

And this is indeed a rather difficult problem, I will continue to pay attention to possible solutions related to this.
